DROP TABLE IF EXISTS Tasks.TaskTaskCategories;
DROP TABLE IF EXISTS Tasks.Tasks;
DROP TABLE IF EXISTS Tasks.TaskCategories;
DROP TABLE IF EXISTS Tasks.TaskStates;
DROP TABLE IF EXISTS Users.UserGroupUsers;
DROP TABLE IF EXISTS Users.UserGroups;
DROP TABLE IF EXISTS Users.Users;
DROP TABLE IF EXISTS Users.Roles;

DROP SCHEMA IF EXISTS Tasks;
DROP SCHEMA IF EXISTS Users;
GO

CREATE SCHEMA Tasks;
GO

CREATE SCHEMA Users;
GO

CREATE TABLE Users.Roles (
	RoleID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(64) NOT NULL UNIQUE,
	CanCreateTasks BIT NOT NULL,
	CanAssignTasks BIT NOT NULL,
	CanDeleteTasks BIT NOT NULL,
	CanModifyTasks BIT NOT NULL
);

CREATE TABLE Users.Users (
	UserID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(64) NOT NULL UNIQUE,
	Email NVARCHAR(64) NOT NULL UNIQUE,
	PasswordHash VARCHAR(64) NOT NULL
);

CREATE TABLE Users.UserGroups (
	UserGroupID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	GroupOwnerID INT NOT NULL FOREIGN KEY
		REFERENCES Users.Users(UserID),
	[Name] NVARCHAR(64) NOT NULL UNIQUE,
	[Description] NVARCHAR(512) NOT NULL
);

CREATE TABLE Users.UserGroupUsers (
	UserGroupID INT NOT NULL FOREIGN KEY
		REFERENCES Users.UserGroups(UserGroupID),
	UserID INT NOT NULL FOREIGN KEY
		REFERENCES Users.Users(UserID),
	RoleID INT NOT NULL FOREIGN KEY
		REFERENCES Users.Roles(RoleID),

	CONSTRAINT Users_UserGroupUsers_UserGroupID_UserID PRIMARY KEY(UserGroupID, UserID)
);

CREATE TABLE Tasks.TaskStates (
	TaskStateID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(64) NOT NULL,
	[Description] NVARCHAR(512) NOT NULL,
	Color CHAR(6) NOT NULL DEFAULT('000000')
);

CREATE TABLE Tasks.Tasks (
	TaskID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Name NVARCHAR(64) NOT NULL,
	Description NVARCHAR(256) NOT NULL,
	OwnerUserID INT FOREIGN KEY
		REFERENCES Users.Users(UserID),
	TaskStateID INT FOREIGN KEY
		REFERENCES Tasks.TaskStates(TaskStateID),
	DueDate DATETIME2 NOT NULL,
	StartDate DATETIME2 NOT NULL,
	CompletionDate DATETIME2 NOT NULL
);

CREATE TABLE Tasks.TaskCategories (
	TaskCategoryID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	OwnerID INT FOREIGN KEY
		REFERENCES Users.Users(UserID),
	[Name] NVARCHAR(64) NOT NULL UNIQUE,
	[Description] NVARCHAR(512),
	Color CHAR(6) NOT NULL DEFAULT(N'000000')
);

CREATE TABLE Tasks.TaskTaskCategories (
	TaskID INT NOT NULL,
	TaskCategoryID INT NOT NULL

	CONSTRAINT Tasks_TaskTaskCategories_TaskID_TaskCategoryID PRIMARY KEY(TaskID, TaskCategoryID)
)